version: '3.8'

services:

  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html

  # Nginx Service
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d # Mount the Nginx config
      - .:/var/www/html:ro # Mount the application code as read-only
    depends_on:
      - php