# fly.toml app configuration file generated for shfc-forum on 2024-01-02T09:35:36-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shfc-forum"
primary_region = "dfw"

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
